---
# .github/workflows/amplify.yml
name: Amplify Security
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]

permissions:
  id-token: write

jobs:
  amplify-security-scan:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: Run Amplify Security Scan (Local)
        uses: amplify-security/runner-action@main
        with:
          amplify-endpoint: https://free-huge-skylark.ngrok-free.app
